"""deeds table

Revision ID: 10680c580735
Revises: 8a85cd72904f
Create Date: 2020-02-13 10:54:08.399845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10680c580735'
down_revision = '8a85cd72904f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deed_timestamp'), 'deed', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deed_timestamp'), table_name='deed')
    op.drop_table('deed')
    # ### end Alembic commands ###
