"""new fields in user model

Revision ID: 7b13cba771be
Revises: 10680c580735
Create Date: 2020-02-23 10:34:08.311683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b13cba771be'
down_revision = '10680c580735'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deed', sa.Column('title', sa.String(length=25), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('deed', 'title')
    # ### end Alembic commands ###
