"""empty message

Revision ID: eda740b9e54c
Revises: 7b13cba771be
Create Date: 2020-02-24 13:59:31.891372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eda740b9e54c'
down_revision = '7b13cba771be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('group', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'group')
    # ### end Alembic commands ###
